import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });
const goatproduct = localfont({
  src: [
    {
      path: "../../public/fonts/GOATProductVariableVF.woff2",
      weight: "400",
    },
  ],
  variable: "--font-goatproduct",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${goatproduct.variable}`}>
        {children}
      </body>
    </html>
  );
}
